name: Publish to TestPyPI
"on":
  workflow_dispatch:

permissions: {}

jobs:
  build-and-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    environment: publish-testpypi
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1  # v8.3.1
        with:
          enable-cache: false
      - run: uv build
      - uses: actions/attest-build-provenance@v4
        with:
          subject-path: 'dist/*'
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
