name: Publish
"on":
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    environment: publish-pypi
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          enable-cache: false
      - run: uv build
      - uses: actions/attest-build-provenance@v4
        with:
          subject-path: 'dist/*'
      - uses: pypa/gh-action-pypi-publish@release/v1
