name: Publish to TestPyPI
"on":
  workflow_dispatch:

permissions: {}

jobs:
  build-and-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    environment: publish-testpypi
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
        with:
          enable-cache: false
      - run: uv build
      - uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: 'dist/*'
      - uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          repository-url: https://test.pypi.org/legacy/
